on:
  push:
    branches:
    - main
  pull_request:
    paths:
    - 'java-shared-dependencies/**'
name: shared-dependencies version check
jobs:
  upper-bound-check:
    name: Shared Dependencies BOM upper-bound check
    runs-on: ubuntu-latest
    if: github.repository_owner == 'googleapis'
    steps:
    - uses: actions/checkout@v2
    - uses: stCarolas/setup-maven@v4
      with:
        maven-version: 3.8.1
    - uses: actions/setup-java@v1
      with:
        java-version: 11
    - run: java -version
    - name: Install Sharee Dependencies BOM locally
      run: |
        mvn -B -V -ntp install --also-make --projects \
          java-shared-dependencies,java-shared-dependencies/first-party-dependencies,java-shared-dependencies/third-party-dependencies
    - name: Install java-core (part of java-shared-dependencies) locally
      # Because java-core uses shared dependencies BOM, this comes later
      run: |
        mvn -B -V -ntp install -DskipTests --also-make -f java-core
    - name: Check the BOM content satisfies the upper-bound-check test case
      run: mvn -B -V -ntp verify -Dcheckstyle.skip
      working-directory: java-shared-dependencies/upper-bound-check